name: scrape-stats
on:
  schedule:
    # Every day of August @ 3:30am EST (7:30 UTC)
    - cron: '30 7 * 8 *'
    # Days 1-15 of September @ 3:30am EST (7:30 UTC)
    - cron: '30 7 1-15 9 *'
    # Every Tuesday of all other months @ 3:30am EST (7:30 UTC)
    - cron: '30 7 * 1-7,10-12 2'
jobs:
  scrape-stats:
    runs-on: macos-latest
    steps:
      - name: Checkout Chron Branch
        uses: actions/checkout@v3
        with:
          ref: cron/update-stats
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          check-latest: true
          cache-dependency-path: package-lock.json
      - run: node scraper.js
