name: scrape-stats
on: 
  schedule:
    #every day of August @ 2:30am
    -chron: 08 11 * 8 * 
    #days 1-15 of September @ 2:30am
    -chron: 30 2 1-15 9 *
    #every Tuesday of all other months @ 2:30am
    -chron: 30 2 * 1-7,10-12 2
jobs:
  scrape-stats:
    runs-on: macos-latest
    steps:
      - name: Checkout Chron Branch
        uses: actions/checkout@v3
        with:
          ref: chron/update-stats
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          check-latest: true
          cache-dependency-path: package-lock.json
      - run: node scraper.js